INSERT INTO CATEGORY (CATEGORY_NAME) VALUES('American');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES('Italian');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES('Spanish');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES('Mexican');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES('Fast food');

INSERT INTO UNIT_OF_MEASURE (MEASURE) VALUES('Tea spoon');
INSERT INTO UNIT_OF_MEASURE (MEASURE) VALUES('Table spoon');
INSERT INTO UNIT_OF_MEASURE (MEASURE) VALUES('Cup');
INSERT INTO UNIT_OF_MEASURE (MEASURE) VALUES('Pinch');
INSERT INTO UNIT_OF_MEASURE (MEASURE) VALUES('Ounce');
INSERT INTO UNIT_OF_MEASURE (MEASURE) VALUES('Each');
INSERT INTO UNIT_OF_MEASURE (MEASURE) VALUES('Dash');
INSERT INTO UNIT_OF_MEASURE (MEASURE) VALUES('Pint');

INSERT INTO RECIPE (COOK_TIME,CREATED_ON,DESCRIPTION,DIFFICULTY,DIRECTIONS,IMAGE,PREP_TIME,SERVINGS,SOURCE,URL,NOTES_ID) VALUES (30, null, 'Burguer', 'EASY', '', null, 60, 4, null, null, null);